# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d82eddbd8668fd75cf27590c8b373e1e5810d73b435ba2ed29f4551eee1b005e1dd6292d47d075e9abbc047d8e6798b28167348ded9f7b65a7681c0a0ffcbb27

test:
  secret_key_base: 2113948139adf58a25707d42e933d862de53c6e5be27d07ef8cb195d76054703b4bff231f700a510f4d735ce6cdecdca30c6504d479844b48114be759809344e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
